### ISSUE TITLE
Simpify System.FSNotify.readEvents

### ISSUE THREAD

**Issue by feuerbach** [haskell-fswatch/hfsnotify#43]
readEvents does some locking. The purpose of that seems to be to disallow multiple callbacks to overlap.

Is that necessary? It seems to me like a user's responsibility.

**Comment by thomasjm** [comment]
Cleaning up old issues now. For this one, given that it only takes a few lines of code for a user to make `MVar`(s) and do `withMVar` on them, I don't see what kind of helpers are envisioned here. I don't think it's worth the complexity to add locking helpers here, since simple ones are easy for the user to do on their own and more elaborate ones involve trying to anticipate more elaborate locking policies. (The issue is also entangled with debouncing.) I'm going to hit close on this issue, feel free to ping back if anyone disagrees and we can revisit.
